### PR TITLE
Update standard Death Knight archetyper

### PR DESCRIPTION
**Pull request by tomka700**
https://www.hsguru.com/decks?format=2&min_games=50&no_archetype=yes&period=perils&player_class=DEATHKNIGHT

### CODE REVIEW

**Comment by tomka700** [comment]
maybe put buttons above rainbow

**Comment by borisbabic** [comment]
I went in a different direction for DK archetypes. Either way they'll probably need more refinement

**Comment by tomka700** [comment]
The end result looks decent, buttons dk might be too broad

**Comment by borisbabic** [comment]
Is there a deck getting archetyped as buttons that you think shouldn't be?

**Pull request closed without merging**
