### PR TITLE
Add Dead Man's Hand Warrior to wild

### PR DESCRIPTION
**Pull request by tomka700**
"XL Dead Man's Hand Warrior" doesn't fit
https://www.hsguru.com/decks?format=1&min_games=50&no_archetype=yes&period=patch_29.6.2&player_class=WARRIOR&player_deck_includes[]=42766

### CODE REVIEW

**Comment by borisbabic** [comment]
DMH without Marin isn't considered DMH warrior?

**Comment by tomka700** [comment]
DMH and Marin make for an infinite combo, DMH isn't run much outside of this interaction

**Comment by borisbabic** [comment]
15-20% of DMH games don't include Marin

**Comment by tomka700** [comment]
example of the combo in action, you can play a lot of free copies of a card with both in your deck, 2 DMHs alone just make your deck infinite, but not free
https://youtu.be/wRAUtSTQks8?si=o4HcuuXL3ulMEoU3

**Comment by borisbabic** [comment]
I'm asking about the 15-20% without Marin, not about those with Marin.

**Comment by tomka700** [comment]
there is nothing special about those, you can name the Marin DMH combo something else if you have a better idea

**Pull request merged**
